<a href="https://colab.research.google.com/github/ESNAULTQ/Sudoku/blob/main/Sudoku.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PRINTBOARD


In [ ]:


def print_board():
    grille = [[5, 3, 4, 6, 7, 8, 9, 1, 2],
              [6, 7, 2, 1, 9, 5, 3, 4, 8],
              [1, 9, 8, 3, 4, 2, 5, 6, 7],
              [8, 5, 9, 7, 6, 1, 4, 2, 3],
              [4, 2, 6, 8, 5, 3, 7, 9, 1],
              [7, 1, 3, 9, 2, 4, 8, 5, 6],
              [9, 6, 1, 5, 3, 7, 2, 8, 4],
              [2, 8, 7, 4, 1, 9, 6, 3, 5],
              [3, 4, 5, 2, 8, 6, 1, 7, 9]]

    indice_alphabetique = 'abcdefghi'

    print("    1 2 3   4 5 6   7 8 9 ")
    for indice_ligne, newligne in enumerate(grille):
        if indice_ligne % 3 == 0:
            print(" ", ("+" + "-" * 7) * 3 + "+")
        print(indice_alphabetique[indice_ligne], end=" ")
        for indice_col in range(len(newligne)):
            if indice_col % 3 == 0:
                print('|', end=" ")
            print(newligne[indice_col], end=" ")
        print('|')
    print(" ", ("+" + "-" * 7) * 3 + "+")
    print()

print_board()  # Appel de la fonction sans print()


    1 2 3   4 5 6   7 8 9 
  +-------+-------+-------+
a | 5 3 4 | 6 7 8 | 9 1 2 |
b | 6 7 2 | 1 9 5 | 3 4 8 |
c | 1 9 8 | 3 4 2 | 5 6 7 |
  +-------+-------+-------+
d | 8 5 9 | 7 6 1 | 4 2 3 |
e | 4 2 6 | 8 5 3 | 7 9 1 |
f | 7 1 3 | 9 2 4 | 8 5 6 |
  +-------+-------+-------+
g | 9 6 1 | 5 3 7 | 2 8 4 |
h | 2 8 7 | 4 1 9 | 6 3 5 |
i | 3 4 5 | 2 8 6 | 1 7 9 |
  +-------+-------+-------+



GENERATOR

SOLVER


CHECKER


RASSEMBLEMENT

In [4]:
!pip install dokusan
from dokusan import generators
import numpy as np

In [54]:
grille_ligne_fausse = [[5, 3, 4, 6, 7, 8, 9, 1, 2],
                       [6, 7, 2, 1, 9, 5, 3, 4, 8],  # Erreur: 0 à la place de 5
                       [1, 9, 8, 3, 4, 2, 5, 6, 7],
                      [8, 5, 9, 7, 6, 1, 4, 2, 3],
                      [4, 2, 6, 8, 5, 3, 7, 9, 1],
                      [7, 1, 3, 9, 2, 4, 8, 5, 6],
                      [9, 6, 1, 5, 3, 7, 2, 8, 4],
                      [2, 8, 7, 4, 1, 9, 6, 3, 5],
                      [3, 4, 5, 2, 8, 6, 1, 7, 9]]

grille_colonne_fausse = [[5, 3, 4, 6, 7, 8, 9, 1, 2],
                        [6, 7, 2, 1, 9, 5, 3, 4, 8],
                        [1, 9, 8, 3, 4, 2, 5, 6, 7],
                        [8, 5, 9, 7, 6, 1, 4, 2, 3],
                        [4, 2, 6, 8, 5, 3, 7, 9, 1],
                        [7, 1, 3, 9, 2, 4, 8, 5, 6],
                        [9, 6, 1, 5, 3, 7, 2, 8, 4],
                        [2, 8, 7, 4, 1, 9, 6, 3, 5],
                        [3, 4, 5, 2, 8, 6, 1, 7, 9]]  # Erreur: 0 à la place de 4


grille_carre_faux = [[5, 3, 4, 6, 7, 8, 9, 1, 2],
                     [6, 7, 2, 1, 9, 5, 3, 4, 8],
                     [1, 9, 8, 3, 4, 2, 5, 6, 7],
                     [8, 5, 9, 7, 6, 1, 4, 2, 3],
                     [4, 2, 6, 8, 5, 3, 7, 9, 1],
                     [7, 1, 3, 9, 2, 4, 8, 5, 6],
                     [9, 6, 1, 5, 3, 7, 2, 8, 4],
                     [2, 8, 7, 4, 1, 9, 6, 3, 5],
                     [3, 4, 5, 2, 8, 6, 1, 7, 0]]  # Erreur: 0 à la place de 9

In [24]:
rankstr = input("Veuillez-choisir une difficulté allant de 100 à 750:    ")
rank = int(rankstr)

def random_grid():
    arr = np.array(list(str(generators.random_sudoku(avg_rank=rank))))
    gridsavestr = arr.reshape(9, 9).tolist()
    gridsaveint = [[int(x) for x in ligne] for ligne in gridsavestr]
    return gridsaveint

GrilleAleatoire = random_grid()
GrilleAleatoire

print("Grille aléatoire générée : ")
print(np.matrix(GrilleAleatoire))

GrilleAleatoiree = [[0, 0, 0, 1, 0, 8, 0, 0, 0],
                    [8, 1, 0, 3, 0, 0, 4, 0, 7],
                    [4, 0, 0, 0, 5, 0, 0, 1, 3],
                    [0, 2, 3, 7, 8, 0, 0, 0, 0],
                    [0, 0, 4, 5, 6, 0, 3, 7, 0],
                    [0, 7, 6, 0, 0, 0, 0, 0, 0],
                    [2, 0, 0, 6, 0, 4, 0, 3, 5],
                    [0, 3, 1, 0, 7, 0, 9, 0, 4],
                    [0, 0, 0, 9, 0, 0, 0, 8, 0]]



Veuillez-choisir une difficulté allant de 100 à 750:    500
Grille aléatoire générée : 
[[0 3 0 9 0 0 0 0 5]
 [6 0 0 0 8 0 0 0 0]
 [8 5 9 0 0 7 0 2 0]
 [0 0 0 0 0 0 0 7 6]
 [0 0 0 5 0 6 0 0 0]
 [5 0 7 0 1 3 0 9 0]
 [0 1 0 6 3 4 0 0 9]
 [0 0 0 0 0 0 0 6 0]
 [0 0 0 8 0 0 0 1 3]]


In [25]:
def possibilite(row, column, number):
    global GrilleAleatoire

    for i in range(0,9):
        if GrilleAleatoire[row][i] == number:
            return False

    for i in range(0,9):
        if GrilleAleatoire[i][column] == number:
            return False

    x0 = (column // 3) * 3
    y0 = (row // 3) * 3
    for i in range(0,3):
        for j in range(0,3):
            if GrilleAleatoire[y0+i][x0+j] == number:
                return False
    return True



In [26]:
GrilleComplet = None
def resoudre():
    global GrilleAleatoire, GrilleComplet
    for row in range(0,9):
        for column in range(0,9):
            if GrilleAleatoire[row][column] == 0:
                for number in range(1,10):
                    if possibilite(row, column, number):
                        GrilleAleatoire[row][column] = number
                        resoudre()
                        GrilleAleatoire[row][column] = 0
                return
    GrilleComplet = np.matrix(GrilleAleatoire)
    print(GrilleComplet)
    input('Press enter for more solutions')
resoudre()



[[7 3 1 9 4 2 6 8 5]
 [6 2 4 1 8 5 9 3 7]
 [8 5 9 3 6 7 1 2 4]
 [1 4 3 2 9 8 5 7 6]
 [9 8 2 5 7 6 3 4 1]
 [5 6 7 4 1 3 8 9 2]
 [2 1 8 6 3 4 7 5 9]
 [3 9 5 7 2 1 4 6 8]
 [4 7 6 8 5 9 2 1 3]]
Press enter for more solutions


In [27]:
GrilleComplete = GrilleComplet.tolist()
GrilleComplete

[[7, 3, 1, 9, 4, 2, 6, 8, 5],
 [6, 2, 4, 1, 8, 5, 9, 3, 7],
 [8, 5, 9, 3, 6, 7, 1, 2, 4],
 [1, 4, 3, 2, 9, 8, 5, 7, 6],
 [9, 8, 2, 5, 7, 6, 3, 4, 1],
 [5, 6, 7, 4, 1, 3, 8, 9, 2],
 [2, 1, 8, 6, 3, 4, 7, 5, 9],
 [3, 9, 5, 7, 2, 1, 4, 6, 8],
 [4, 7, 6, 8, 5, 9, 2, 1, 3]]

In [53]:
def check_sudoku(grille):
  for ligne in grille:
    if not len(set(ligne)) == 9:
      return False
    if 0 in ligne:
            return False
  for i in range(9):
    colonne = []
    for j in range(9):
      colonne.append(grille[j][i])
    if not len(set(colonne)) == 9:
      return False
    if 0 in colonne:
            return False

  for y0 in [0, 3, 6]:
   for x0 in [0, 3, 6]:
    grille2 = []
    for i in range(0,3):
        for j in range(0,3):
          if grille[y0+i][x0+j] in grille2:
             return False
             grille2.append(grille[y0+i][x0+j])
          if grille[y0+i][x0+j] == 0:
                        return False

  return True

print(check_sudoku(GrilleComplet))


False
